---
# tasks file for win_ad_user
 - include_vars: users.yml
 - name: add AD user
   win_domain_user:
        name: "{{ item.name }}"
        firstname: "{{ item.firstname }}"
        surname: "{{ item.lastname }}"
        password: "{{ item.password }}"
        state: present
   with_items:
        - "{{ user_info }}"
